# Generated by Django 5.1.1 on 2024-10-31 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_media_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.CharField(max_length=10, verbose_name='Número')),
                ('complement', models.CharField(max_length=255, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=10, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Mídia', 'verbose_name_plural': 'Mídias'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Parceiro', 'verbose_name_plural': 'Parceiros'},
        ),
        migrations.AlterModelOptions(
            name='planpartner',
            options={'verbose_name': 'Plano de Parceiro', 'verbose_name_plural': 'Planos de Parceiros'},
        ),
        migrations.AlterModelOptions(
            name='quatrain',
            options={'verbose_name': 'Quadra', 'verbose_name_plural': 'Quadras'},
        ),
        migrations.AlterField(
            model_name='client',
            name='cnpj',
            field=models.CharField(max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='media',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='core.partner'),
        ),
        migrations.AlterField(
            model_name='media',
            name='quatrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quatrains', to='core.quatrain'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='core.address', verbose_name='Endereço'),
        ),
    ]
